include(Platform/Darwin-GNU)
__darwin_compiler_gnu(OBJC)
cmake_gnu_has_isysroot(OBJC)
cmake_gnu_set_osx_deployment_target_flag(OBJC)

set(CMAKE_OBJC_FLAGS_INIT "")
set(CMAKE_OBJC_FLAGS_DEBUG_INIT "-g")
set(CMAKE_OBJC_FLAGS_MINSIZEREL_INIT "-Os")
set(CMAKE_OBJC_FLAGS_RELEASE_INIT "-O3")
set(CMAKE_OBJC_FLAGS_RELWITHDEBINFO_INIT "-O2 -g")
set(CMAKE_OBJC_CREATE_PREPROCESSED_SOURCE "<CMAKE_C_COMPILER> <FLAGS> -E <SOURCE> > <PREPROCESSED_SOURCE>")
set(CMAKE_OBJC_CREATE_ASSEMBLY_SOURCE "<CMAKE_C_COMPILER> <FLAGS> -S <SOURCE> -o <ASSEMBLY_SOURCE>")


